const express = require('express');
const { signUp, signIn, signInByRefreshToken, noGuard } = require('../services/public/authentication');
const { tradingRooms, latestKlines, latestRounds, tradingConfig, getBestTrader, getTradingRoomBySymbol } = require('../services/public/tradingService');
const { getNotifications } = require('../services/public/userService');
const { getAppConfig } = require('../services/public/appConfigService');
const { getLatestNews } = require('../services/public/landingService');
const { getPartnerRegistrations } = require('../services/public/publicService');
const publicRoute = express.Router();

publicRoute.post('/sign-up', signUp);
publicRoute.post('/sign-in', signIn);
publicRoute.post('/sign-in/refreshToken', signInByRefreshToken);
publicRoute.get('/trading/rooms', tradingRooms);
publicRoute.get('/trading/rooms/:symbol', getTradingRoomBySymbol);
publicRoute.get('/trading/rooms/:symbol/klines/latest', latestKlines);
publicRoute.get('/trading/rooms/:symbol/rounds/latest', latestRounds);
publicRoute.get('/trading/rooms/:symbol/config', tradingConfig);
publicRoute.get('/notifications', noGuard, getNotifications);
publicRoute.get('/appConfig', getAppConfig);
publicRoute.get('/bestTraders', getBestTrader);
publicRoute.get('/news', getLatestNews);
publicRoute.get('/partnerRegistrations', getPartnerRegistrations);
module.exports = publicRoute;