
on:
    push:
      branches:
      - master
jobs:
    update-production:
      runs-on: ubuntu-latest
      steps:
      - name: Update production and restart gateway
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
                  whoami
                  cd /usr/share/nginx/stake
                  git fetch --all
                  git reset --hard origin/master
                  git pull origin master
                  cd stake-gateway
                  rm -rf node_modules
                  rm -rf package-lock.json
                  yes | cp .pd.env .env
                  npm i
                  pm2 restart 0