
# on:
#     push:
#       branches:
#       - master
# jobs:
#     build-web:
#         runs-on: ubuntu-latest
#         defaults:
#             run:
#                 working-directory: ./stake-web
#         permissions:
#           contents: write
#         steps:
#             - uses: actions/checkout@v3
#             - uses: actions/setup-node@v1 #this installs node and npm for us
#               with:
#                 node-version: "14.x"
#             - uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
#               with:
#                 path: ~/.npm
#                 key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#                 restore-keys: |
#                     ${{ runner.os }}-node-
#             - name: Prepare
#               run: |
#                     npm cache clean --force
#                     npm install
#                     npm install -g @angular/cli > /dev/null
#             - name: Auto build
#               run: |
#                     npm version patch
#                     npm run build
#             - name: Process production config
#               run: yes | cp -rf ./dist/assets/json/config.pd.json ./dist/assets/json/config.json
#             - name: Auto commit
#               uses: stefanzweifel/git-auto-commit-action@v4
#               with:
#                 commit_message: Auto build web
#                 branch: master
#                 commit_options: '--no-verify --signoff'
#                 add_options: '-u'
#                 push_options: '--force'
#                 skip_dirty_check: true
#                 skip_fetch: true
#                 skip_checkout: true
#                 disable_globbing: true
#                 create_branch: true
#             # - run: sudo sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_ADDRESS }} 'rm -rf /usr/share/nginx/stake/stake-web/dist/*'
#             # - run: |
#             #         cd dist
#             #         tar -czvf ../dist.tar.gz ./
#             #         cd ..
#             #         sudo sshpass -p ${{ secrets.SERVER_PASSWORD }} scp -r dist.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_ADDRESS }}:/usr/share/nginx/stake/stake-web/dist
#             # - run : sudo sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_ADDRESS }} 'cd /usr/share/nginx/stake/stake-web/dist && tar -xzvf dist.tar.gz && rm -rf dist.tar.gz'
#             # - run : sudo sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_ADDRESS }} 'cp -f /usr/share/nginx/stake/stake-web/dist/assets/json/config.pg.json /usr/share/nginx/stake/stake-web/dist/assets/json/config.json'
#     build-admin:
#       runs-on: ubuntu-latest
#       defaults:
#           run:
#               working-directory: ./stake-admin
#       permissions:
#         contents: write
#       steps:
#           - uses: actions/checkout@v3
#           - uses: actions/setup-node@v1 #this installs node and npm for us
#             with:
#               node-version: "14.x"
#           - uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
#             with:
#               path: ~/.npm
#               key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#               restore-keys: |
#                   ${{ runner.os }}-node-
#           - name: Prepare
#             run: |
#                   npm cache clean --force
#                   npm install
#                   npm install -g @angular/cli > /dev/null
#           - name: Auto build
#             run: |
#                   npm version patch
#                   npm run build
#           - name: Process production config
#             run: yes | cp -rf ./dist/assets/json/config.pd.json ./dist/assets/json/config.json
#           - name: Auto commit
#             uses: stefanzweifel/git-auto-commit-action@v4
#             with:
#               commit_message: Auto build admin
#               branch: master
#               commit_options: '--no-verify --signoff'
#               add_options: '-u'
#               push_options: '--force'
#               skip_dirty_check: true
#               skip_fetch: true
#               skip_checkout: true
#               disable_globbing: true
#               create_branch: true
#     update-production:
#       needs: [build-web, build-admin]
#       runs-on: ubuntu-latest
#       steps:
#       - name: Update production and restart gateway
#         uses: appleboy/ssh-action@v0.1.10
#         with:
#           host: ${{ secrets.SERVER_ADDRESS }}
#           username: ${{ secrets.SERVER_USER }}
#           password: ${{ secrets.SERVER_PASSWORD }}
#           script: |
#                   whoami
#                   cd /usr/share/nginx/stake
#                   git fetch --all
#                   git reset --hard origin/master
#                   git pull
#                   cd stake-gateway
#                   rm -rf node_modules
#                   rm -rf package-lock.json
#                   npm i
#                   pm2 restart 0
#                   systemctl restart nginx